### ISSUE TITLE
Twitch status poll should not run if Twitch is not configured!

### ISSUE THREAD

**Issue by ashkeel** [strimertul/strimertul#17]
Relevant panic data:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0x7037ba]

goroutine 83 [running]:
github.com/strimertul/strimertul/modules/twitch.(*Client).runStatusPoll.func1(0xc00007b2c0)
        E:/DEV/strimertul/modules/twitch/client.go:149 +0x5a
github.com/strimertul/strimertul/modules/twitch.(*Client).runStatusPoll(0xc00007b2c0)
        E:/DEV/strimertul/modules/twitch/client.go:161 +0x51
created by github.com/strimertul/strimertul/modules/twitch.Register
        E:/DEV/strimertul/modules/twitch/client.go:74 +0x3ef
```

**Comment by ashkeel** [comment]
Fixed in a6b8ffa87733e6827c03f9becde5732b17ea6ddd
